name: Post daily hamster

on:
  schedule:
    # JST 09:00 = UTC 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run poster
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python post_hamster.py

      - name: Commit used.json if changed
        run: |
          if ! git diff --quiet -- used.json 2>/dev/null; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add used.json
            git commit -m "chore: update used hamster keys [skip ci]"
            git push
          else
            echo "No changes to used.json"
          fi
